### ISSUE TITLE
History of changes to the system done by the user

### ISSUE THREAD

**Issue by nilhoel1** [openSUSE/transactional-update#108]
Hi,

I have been trying to find if transactional-update keeps a list of changes done by the user.
As this would allow to quickly set up a nearly identical system on another machine.

Does a feature like this exist?

Best,
Nils H.

**Comment by laenion** [comment]
In general the operations are logged in /var/log/transactional-update.log; what you may be looking for are the lines starting with `xxxx-xx-xx xx:xx Options: `. These could then be called again.
What is **not** logged are commands entered by the user during a `shell` session though (or any interactive input in general).
