### ISSUE TITLE
Allow automatically accepting license agreements

### ISSUE THREAD

**Issue by MrIngelborn** [openSUSE/transactional-update#114]
I have an NVIDIA card and am using the proprietary drivers. Every update requires the user to accept (the same) license agreements. The default option is no so the installations fails during during the automatic transactional updates. So every time the NVIDIA drivers have an update I have to run transactional-update in interactive mode. Often I miss a few days or weeks of updates before I realize that the updates have not been successful.

Would be great if the licenses could be automatically agreed upon with a flag or property in a config file. Maybe even one per package if you wanna be on the safe side.

**Comment by laenion** [comment]
We discussed this some time ago, but decided to not add the `--auto-agree-with-licenses` option by default for legal reasons - agreeing to a license has to be a conscious decision by the user.

However you can just set the option with zypper: the `autoAgreeWithLicenses` option in _/etc/zypp/zypper.conf_ will have the same effect - permanently.

(For a future implementation it may be worth considering to accept options for the `up`, `dup` and `patch` commands, i.e. everything that follows will be forwarded to zypper; currently everything after these commands is just discarded...)
