### ISSUE TITLE
[Feature/usability] Allow multiple package installations or prompt user before discarding

### ISSUE THREAD

**Issue by CySlider** [openSUSE/transactional-update#16]
As a newbie to this I stumbled quite hard about the fact that you can only use one transactional-update pkg in <packagelist> command before rebooting.

Intuitively I assumed that I could run multiple such modifications and they all would apply after the next reboot.

So I would suggest to either allow this or be more vocal about losing changes made before. I only spotted the relevant lines in the logs after being irritated why changes were still not there after reboot.

    WARNING: Default snapshot differs from current snapshot.
    WARNING: Any changes within the previous snapshot will be discarded!

Maybe instead prompt the user like:
    You have changes that require a reboot to be in effect. If you continue, those changes will be lost. Continue? [n/y]

**Comment by thkukuk** [comment]
On Tue, Sep 25, Torge Kummerow wrote:

> As a newbie to this I stumbled quite hard about the fact that you can only use
> one transactional-update pkg in command before rebooting.

But it is quite logical: you never know if the newer snapshots are
working or not. If you use them and they don't work, you have a
broken system from which you cannot recover anymore.

> Maybe instead prompt the user like:
> You have changes that require a reboot to be effective. If you continue, those
> changes will be lost. Continue? [n/y]

Beside that this does not need to be correct (see above), this kind
of prompt will only trigger the next wave of bug reports to remove
that again. We made this experience already with other tools for
package management.

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & CaaSP
SUSE LINUX GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nuernberg)

**Comment by CySlider** [comment]
> On Tue, Sep 25, Torge Kummerow wrote: As a newbie to this I stumbled quite hard about the fact that you can only use one transactional-update pkg in command before rebooting.
> But it is quite logical: you never know if the newer snapshots are working or not. If you use them and they don't work, you have a broken system from which you cannot recover anymore.

Sorry, I think I was not clear what I meant. I meant it working analogous to database transactions.
You have a begin transaction, then you can do any number of actions and finally you commit.
Begin transaction would be bootup. commit would be reboot. So the idea is to be able to run multiple  `transactional-update pkg in` commands to define the new state the system should be in after reboot. The old, rollback state should be still the current system ofc.

I say this, as most tutorials I followed in my life, don't start with installing all packages in a single command. So I fell to this trap as I was walking through my own notes of how I did set up the Leap 42.2. Not suspecting only the last command being the one that wins.

> Maybe instead prompt the user like: You have changes that require a reboot to be effective. If you continue, those changes will be lost. Continue? [n/y]
> Beside that this does not need to be correct (see above), this kind of prompt will only trigger the next wave of bug reports to remove that again. We made this experience already with other tools for package management.

I bet there are other ways of solving this. I only tell you my personal usability issue and I think there is room for improvements, especially in the realm of "first impression" But I also might just be too stupid. Can't know for myself.

**Comment by thkukuk** [comment]
On Tue, Sep 25, Torge Kummerow wrote:

>     On Tue, Sep 25, Torge Kummerow wrote: As a newbie to this I stumbled quite
>     hard about the fact that you can only use one transactional-update pkg in
>     command before rebooting.
>     But it is quite logical: you never know if the newer snapshots are working
>     or not. If you use them and they don't work, you have a broken system from
>     which you cannot recover anymore.
> 
> Sorry, I think I was not clear what I meant. I meant it working analogous to
> database transactions.
> You have a begin transaction, then you can do any number of actions and finally
> you commit.
> Begin transaction would be bootup. commit would be reboot. So the idea is to be
> able to run multiple transactional-update pkg in commands to define the new
> state the system should be in after reboot. The old, rollback state should be
> still the current system ofc.

If you compare it with your analogy of database transactions:
- you begin a transaction
- you do a number of actions
- you don't close it (no reboot)
- you start a second transaction
- you do a number of actions
- you don't close it (no reboot)
- you start a third transaction
- you do a number of actions
- you close it (reboot)

Which means, you have two not closed transactions and one closed
one. We ignore not closed/finished transactions and use the third,
closed transaction. You cannot start a new transaction based on
something, which is not yet completed.

If you know a better way to warn people, except the already existing
warning, and don't annoy them with this, we will be happy to implement
that.

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & CaaSP
SUSE LINUX GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nuernberg)

**Comment by laenion** [comment]
For now if you want to "stack" changes you can use `transactional-update shell` and execute any commands (e.g. multiple _zypper_ commands) there. That way you will only get one snapshot / transaction.

I'd love to implement the ability to stack changes, especially as this is a popular feature request. However we rely on snapper for snapshot creation which will always use the currently mounted system as a base. To enable change stacking snapper would have to be extended to be able to create a snapshot of a different snapshot. I didn't have a look at the feasibility of that yet.

**Comment by CySlider** [comment]
@laenion Thanks for confirming that this is not the worst idea. Also your solution is already a very good workaround for me. This seems to do most of what I would expect. :-)

@thkukuk I did not say, that  we need support for multiple parallel transactions or that you are able to begin one manually. I said the boot should by default open a new transaction and the reboot should close it. If this is accessible via special commands, opening a new transaction while one is still open could simply be prohibited or roll back the previous one.

**Comment by ITwrx** [comment]
I'm evaluating Opensuse right now, have installed a transaction update server role, and I think the desired behavior should be that the user should be able to add (and remove) proposed changes to the transaction, preferably without having to know what they will all be, and able to be entered in/at different commands/times. It should be transparent, so that there isn't a separate procedure for using it this way. IOW, if i haven't rebooted, then it's all just proposed and can be manipulated. You should be able to see all proposed changes and edit easily, if you can't already. As one possible CLI example, UFW handles view+edit in an easy to use way with "ufw status numbered" and "ufw delete 3".   

I would think this would also allow more flexibility for using transactional update with desktop Opensuse, with it's likelyhood for more package updates/changes and make managing a transactional update OS role much more convenient and intuitive. For desktop, it would be nice if the proposed changes to the transaction, and edit capability, were in the package management GUI for people who are using one.
thanks

**Comment by laenion** [comment]
Support for branching off a different snapshot is currently being implemented in snapper, as soon as this is finished we can also (finally) implement this feature in transactional-update.

The current state is that snapper will probably get a new `--from` parameter to specify the origin.

On the transactional-update side we can put some syntactical sugar on top of it. The plan was to add a command line option such as `--continue [<num>]` to resume a snapshot, i.e. by default a transactional-update run would still create a new snapshot as it does now. I'll have to think a bit more about continuing snapshots by default - this may indeed make it easier to integrate transactional-update into Salt or other configuration management software.

Regarding viewing the changes: That's already built in into snapper (`snapper diff <num1>..<num2>`).

What I won't be implementing is some kind of snapshot merging where you would be able to remove or add the contents of certain snapshots, that's way beyond the original scope...

**Comment by ITwrx** [comment]
Thanks for the explanation. There's a good chance i just need to use this more, especially after the new work you refer to.
