### ISSUE TITLE
[FR] Auto rollback option a la microOS

### ISSUE THREAD

**Issue by ITwrx** [openSUSE/transactional-update#21]
IDK if this belongs here or in snapper repo, but it would be nice if tumbleweed transactional update role(s) could support auto rollback on error like microOS does.
thanks

**Comment by laenion** [comment]
The project is called **health-checker** and can be found here: https://github.com/kubic-project/health-checker.

Are you aware that the package `health-checker` is part of Tumbleweed and Leap can simply be installed there? To permanently enable the service use `systemctl enable health-checker.service`.

Or do you explicitly want the package to be part of the _Transactional Server_ role?

**Comment by ITwrx** [comment]
ahh, cool. I find this feature exciting b/c after i found out about the Transactional Server role i thought of this exact idea (just check for a list of services and rollback on failure) and was thinking to try to do the same thing. When i found out opensuse devs had already thought of it and implemented it, that makes a good impression.

no, i didn't know you could just install it, enable it and use it in Tumbleweed and Leap. that's awesome.

Does it already work (if installed and enabled) with the Transactional Server role too? Either way, I think it makes sense to have it included and enabled by default with the Transactional Server role since auto update is already enabled by default, and it might as well handle the possibility of a failure after that update. I see a good use case for Transactional Server in remote client locations and i wouldn't want it to restart after an autoupdate, fail and do nothing. Because then you find out from the client instead of the machine. :)

**Comment by thkukuk** [comment]
It does not make sense to enable health-checker by default on the Transactional Server Role. On MicroOS, the workload runs in container, but with Transactional Server, the workload runs in the system. This can have quite some negative side effects during an automatic rollback. Beside that health-checker has not tests for this workload, you need to write some at your own at first.

**Comment by ITwrx** [comment]
oh, ok. i haven't even used btrfs before, so i wan't aware of that. Thanks for the info, i'll look into it.
