### ISSUE TITLE
I enable transactional-update, but my pc reboot itself with rebootmgr disabled.

### ISSUE THREAD

**Issue by kevinsmia1939** [openSUSE/transactional-update#23]
I'm on desktop opensuse TW.
I want to try out transactional-update so I enable it with

systemctl enable --now transactional-update.timer

Following this guide https://kubic.opensuse.org/blog/2018...tionalupdates/

I did not enable rebootmgr.service
So I wait 24 hrs later until transactional-update start on 1:48 AM. But it suddenly reboot. I have no idea what make it reboot.

No rebootmgr service found running on my system.
systemctl status rebootmgr
Unit rebootmgr.service could not be found.

This is my systemctl list-timers -all

Any clue? Thanks.

```
jaja@linux-eerr:~> systemctl list-timers -all
NEXT                         LEFT        LAST                         PASSED             UNIT                         ACTIVATES
Sun 2020-01-26 03:00:00 GMT  30min left  Sun 2020-01-26 02:00:00 GMT  29min ago          snapper-timeline.timer       snapper-timeline.service
Mon 2020-01-27 00:00:00 GMT  21h left    Mon 2020-01-20 00:00:30 GMT  6 days ago         btrfs-balance.timer          btrfs-balance.service
Mon 2020-01-27 00:00:00 GMT  21h left    Mon 2020-01-20 00:00:30 GMT  6 days ago         fstrim.timer                 fstrim.service
Mon 2020-01-27 00:00:00 GMT  21h left    Sun 2020-01-26 00:00:15 GMT  2h 29min ago       logrotate.timer              logrotate.service
Mon 2020-01-27 00:00:00 GMT  21h left    Sun 2020-01-26 00:00:15 GMT  2h 29min ago       mandb.timer                  mandb.service
Mon 2020-01-27 00:00:00 GMT  21h left    Sun 2020-01-26 00:00:15 GMT  2h 29min ago       unbound-anchor.timer         unbound-anchor.service
Mon 2020-01-27 00:27:36 GMT  21h left    Sun 2020-01-26 01:36:24 GMT  53min ago          backup-rpmdb.timer           backup-rpmdb.service
Mon 2020-01-27 00:37:39 GMT  22h left    n/a                          n/a                transactional-update.timer   transactional-update.service
Mon 2020-01-27 01:07:12 GMT  22h left    Sun 2020-01-26 01:11:42 GMT  1h 17min ago       check-battery.timer          check-battery.service
Mon 2020-01-27 01:29:04 GMT  22h left    Sun 2020-01-26 00:37:36 GMT  1h 51min ago       backup-sysconfig.timer       backup-sysconfig.service
Mon 2020-01-27 01:59:10 GMT  23h left    Sun 2020-01-26 01:59:10 GMT  30min ago          snapper-cleanup.timer        snapper-cleanup.service
Mon 2020-01-27 02:03:57 GMT  23h left    Sun 2020-01-26 02:03:57 GMT  25min ago          systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Sat 2020-02-01 00:00:00 GMT  5 days left Wed 2020-01-01 08:33:11 GMT  3 weeks 3 days ago btrfs-scrub.timer            btrfs-scrub.service

13 timers listed.
```

**Comment by kevinsmia1939** [comment]
I also ask the same question here: https://forums.opensuse.org/showthread.php/538891-transactional-update-timer-reboot-my-pc-even-if-bootmgr-timer-is-disabled

**Comment by laenion** [comment]
`transactional-update.timer` will call transactional-update with the `reboot` option; as the option name implies this will try to reboot the system in case any update was applied. If nothing is configured explicitly then the `auto` value from https://kubic.opensuse.org/documentation/man-pages/transactional-update.conf.5.html#auto is assumed; as `rebootmgr` is not installed it will fall back to `systemctl reboot`, which means that it will reboot the system immediately after the update.

You could either configure transactional-update to use `none` as the reboot method (https://kubic.opensuse.org/documentation/man-pages/transactional-update.conf.5.html#none), or you change the systemd timer to call transactional-update without the `reboot` option.

**Comment by kevinsmia1939** [comment]
Thanks, will try it out.
