### ISSUE TITLE
[Question] transactional server role in systemd-nspawn container?

### ISSUE THREAD

**Issue by ITwrx** [openSUSE/transactional-update#28]
Hi,
Is it currently possible to use Transactional Server as guest OSes in systemd-nspawn containers? I found instructions for installing regular Tumbleweed as guests, but don't know how to modify that to install Transactional Server instead. 

Or i just need to use regular tumbleweed as guests and install transactional-update?

why: i want my guests (and the Transactional Server host) to update themselves without breaking.

thanks,
ITwrx

**Comment by laenion** [comment]
No, that's currently not possible. systemd-nspawn is basically an extended chroot environment, but takes several concepts from container deployments. You won't have access to physical devices or btrfs subvolumes from within the container.
It may be possible to map all of these into the container, but that's not how you would usually work with a container. But feel free to experiment with it :-)

Maybe the `systemd-nspawn --template` option to update the container from the host before deploying it could be interesting for you.

**Comment by ITwrx** [comment]
ok, thanks a lot for the detailed answer.
