### ISSUE TITLE
Can't install hp-plugins with Transactional Desktop.

### ISSUE THREAD

**Issue by ITwrx** [openSUSE/transactional-update#29]
My hp laserjet MFP requires the proprietary plugins [!] and i have it connected to a computer that is running a makeshift Transactional Desktop. hp-plugin fails with some vague error. I suspect it is trying to write somewhere that is read only. Any ideas on a workaround? I don't know where it's trying to write or i guess I could allow writing there.
Thanks

**Comment by laenion** [comment]
Please describe what you did: What exactly did you download, how did you install it, and what was (even vague) the error message?

**Comment by ITwrx** [comment]
sorry i assumed everyone has had the joy of playing with HP's printer plugin nonsense. :)

i downloaded 
https://developers.hp.com/sites/default/files/hplip-3.19.12-plugin.run
https://developers.hp.com/sites/default/files/hplip-3.19.12-plugin.run.asc
which was the latest at the time. I also tried another version with the same results, even though i don't think it has to do with a bug in the plugin installer.

I ran "hp-plugin -g".

I selected "install an existing local copy of the plugin file", as the option to download from hp fails a lot due to key servers, etc.

The result is "Plugin Installation Failed." (the vague message i referenced)

and

"Error: Python gobject/dbus may not be installed" (the msg i didn't mention. :))

I have python3-gobject, python-gobject2, python-gobject-common-devel, python3-gobject-devel, python3-dbus-python, and python-dbus-python-common-devel installed.

I think it's trying to write somewhere it can't write to, b/c hp-plugin installs the plugin successfully on the normal TW (same printer and computer, previous normal TW install). I don't think i had to do anything special with normal TW except install from previously downloaded files due to install script limitations/assumptions and key server issues.

thanks

**Comment by ITwrx** [comment]
https://bugs.launchpad.net/hplip/+bug/1831091

**Comment by laenion** [comment]
I just tested this now - this is mostly a problem with bad error logging of the hplip plugin. It needs both a graphical environment for the root user and the package `sane-backends` installed.

One way to install it (using the console interface):

As root:
```
transactional-update pkg in sane-backends
transactional-update -c shell
cd /tmp
<path to>/hplip-xxx-plugin.run --keep
cd plugin_tmp
python3 plugin-install.py --interactive --logging=debug
exit
```

You can also directly use the graphical installer from within the transactional-update environment, but that depends on your system configuration on how to start X applications as _root_.

**Comment by ITwrx** [comment]
i followed your cli instructions (thanks, btw) and the plugin scripts report no errors and seem to install properly. However, after reboot and when trying to print, printing fails with a popup saying that plugins are required. Maybe you didn't/weren't able to actually try printing afterwards?

thanks

**Comment by laenion** [comment]
I don't have any HP printer and cannot test this myself, so I won't be able to provide further any assistance here - I just verified that the installation itself was working.

If you can trigger this error with any hplip application I'd suggest using `strace -f -efile <hpapplication>` and check which files the application is looking for, or check whether there is a debug mode hidden in the software somewhere.
