### ISSUE TITLE
Package texlive is broken because /var/lib is shadowed by another volume

### ISSUE THREAD

**Issue by levaphenyl** [openSUSE/transactional-update#56]
### System info
`/etc/os-release`:
```bash
NAME="openSUSE MicroOS"
# VERSION="20210219"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20210219"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20210219"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo"
```
Version:
`transactional-update 3.1.4`

### How to reproduce
```bash
sudo transactional-update pkg install texlive-collection-latex
# Some warning appear that files in /var/lib are being shadowed by another mounted volume.
# Imprudent user like myself ignores it and reboots. What could possibly go wrong?

# After reboot
pdflatex any_file.tex
> mktexfmt [ERROR]: -user mode but path setup is -sys type, bailing out.

# When trying to fix it
sudo -i
mkdir /run/texlive
touch /run/texlive/run-{hypen,fmtutil.{language,refresh}}
/usr/share/texmf/texconfig/update
> This texlive installation is broken!  # not the exact message
```

Related issue can be found on the [mailing list](https://lists.opensuse.org/archives/list/support@lists.opensuse.org/thread/7JIEYA7T2VSSM34TFPSDZOT2KMPY7CVR). I am not the author but ran into the same issue.

### Analysis
When running `transactional-update shell`, I see the message `Separate /var detected.` and also that only the `/var/log` directory is mounted.
However, the `%post` section of the [`texlive` package](https://build.opensuse.org/package/view_file/openSUSE:Factory/texlive/texlive.spec?expand=1) is calling `/var/run/texlive/run-update` that is implicitly writing to `/var/lib`. But that `/var/lib` is only local to the snapshot and the actual system `/var/lib` is on another partition! Hence the shadowing message.

As a fix, could `transactional-update` mount the entire `/var` directory instead of `/var/log` only?

### Workaround
Read the shadowing message and manually copy the listed files from `/.snapshots/X/snapshot/var/lib/` to `/var/lib/` when outside of the chroot.

**Comment by thkukuk** [comment]
The texlive package should not modify or run anything in /var or /run during a transcational or atomic update. Mounting /var would mean, that the update is no longer "Atomic" and could influence or break the running system. And the goal of atomic updates is exactly that this does not happen.
If texlive needs to modify something below /var, and it is updated by transactional-update, the changes have to be done by the next first boot with this update applied.

**Comment by levaphenyl** [comment]
Thank you for the explanation! It is much clearer why `transactional-update` is not mounting `/var`.
Trying to generalize, the `%post` section of the specfile should be executed after the reboot and not at the end of the install, right?
Having some scripts automatically executed as root on the next successful boot seems like a bad idea for both security and maintenability. However, could the post-script be logged somewhere for the user to retrieve, e.g. using `rpm -qp --scripts`?

**Comment by thkukuk** [comment]
The `%pre` and `%post` sections need to be run during installation and upgrade, as they e.g. could create user accounts to be able to install files with correct ownership. There are only certain things which could not be done in this kind of pre/post install things, like modifying data in /run or /var. So you cannot forbid them in general.
But if you install/update them outside of transactional-update, they need to run.
One way to solve this are oneshot systemd services which run at the next boot to do this jobs.
But in general, it's better to package the code in a way that no pre/post section is needed or at least no modifications in /var/lib required.

**Comment by levaphenyl** [comment]
So it looks specific to the packaging of texlive and the way the LateX packages are installed system-wide.
Thank you for your answers. Closing this issue as it it related to a specific package and not to `transactional-update`.
