### ISSUE TITLE
mark snapshot for cleanup right on creation

### ISSUE THREAD

**Issue by lnussel** [openSUSE/transactional-update#62]
on a microos system that was running for a year I have some snapshots that do not have a cleanup algorithm assigned. Looks like something went wrong back then so the cleanup step didn't work. So would be better to call `snapper create -c ...` right away so a snapshot has cleanup info attached right away.

**Comment by laenion** [comment]
Implemented in https://github.com/openSUSE/transactional-update/commit/d8a58061b784f1ff9a48f0f24358ab2d6ed6c4bd.
