### ISSUE TITLE
Some output remains despite --quiet

### ISSUE THREAD

**Issue by sebix** [openSUSE/transactional-update#69]
With the shell command, I get this:

```
user@microostest:~> sudo /sbin/transactional-update --continue --quiet --drop-if-no-change shell
Opening chroot in snapshot 18, continue with 'exit'
transactional update # exit
user@microostest:~> 
```
I would expect, that `Opening chroot in snapshot 18, continue with 'exit'` is not present

using version 3.5.1 on MicroOS 20210805

**Comment by laenion** [comment]
Indeed, that message doesn't add any value in `--quiet` mode - it was just left as an `echo` to not have it part of the log file. Added a dedicated function for such messages now.
