### ISSUE TITLE
ERROR: filesystem error: cannot copy: Operation not supported [/run/systemd/resolve]

### ISSUE THREAD

**Issue by stuartpb** [openSUSE/transactional-update#70]
I have systemd-resolved running, and I get this error whenever I try to do transactional-update commands:

```
# transactional-update shell
Checking for newer version.
transactional-update 3.5.2 started
Options: shell
Separate /var detected.
2021-09-09 18:09:29 tukit 3.5.2 started
2021-09-09 18:09:29 Options: -c129 open 
2021-09-09 18:09:30 Using snapshot 129 as base for new snapshot 130.
2021-09-09 18:09:30 Syncing /etc of previous snapshot 128 as base into new snapshot "/.snapshots/130/snapshot"
2021-09-09 18:09:31 Discarding snapshot 130.
ERROR: filesystem error: cannot copy: Operation not supported [/run/systemd/resolve] [/.snapshots/130/snapshot/run/systemd/resolve]
transactional-update finished
```

**Comment by stuartpb** [comment]
This looks like an attempt to replicate #44's behavior with the C code in commit 43e4ebd7dafc0700725a8b9ea4c6066bf3dbf0b4, but that's different from what the original shell script did, as it tries to copy the entire directory - including the `io.systemd.Resolve` socket - and not just the `.conf` files, as the old code did.

**Comment by laenion** [comment]
Thanks a lot for the bug report AND the fix!

We indeed don't have a test case for resolved support, so that went unnoticed...

**Comment by stuartpb** [comment]
This is a blocking issue for me: how long until this patch makes it to release, and when it's released, will I be able to run `transactional-update` to get it (since it looks for a new version before starting the transaction)?

**Comment by laenion** [comment]
I just released a new transactional-update version and submitted it to Factory: https://build.opensuse.org/request/show/918476.

transactional-update will automatically update itself as soon as released on Tumbleweed, no special action is necessary to make the update work.
