### ISSUE TITLE
fstab overlay grows without bound

### ISSUE THREAD

**Issue by dannysauer** [openSUSE/transactional-update#72]
Originally reported incorrectly as openSUSE/snapper#669

I can't install updates on read-only root Leap 15.2 any longer because /etc fails to mount when another snapshot is installed.  I think this is because the fstab line is too long (I'm guessing there's a 4096 char limit, since 4088 is ok).  There are a ton of shapshots being overlaid here, and I think they need collapsed to match the actual snapshots instead of keeping them all.

As a result of this situation, I haven't updated since March, as I had to turn off automatic updating (it's aggravating to find a super-stable read-only root server machine rebooted and hung overnight :D).  I'm not really sure how these overlays work, and it's tough to find documentation.  I think there was an update to transactional_update which addressed this, but I can't find that PR now. :/

Do I just manually copy files across the directories?  Is there maybe a script already somewhere which can identify the newest overlay in each of the snapshots, and flatten the intermediate directories into just those, probably also going into the root FS snapshots and updating the corresponding fstab lines to reflect the flattening?

I've stuck what I suspect is the most relevant information about the system below. :)  I should probably delete snapshots 199 and 200, but that's really not the most pressing issue here. ;)

```
sauer@orthos:~> lsb_release -a
LSB Version:	n/a
Distributor ID:	openSUSE
Description:	openSUSE Leap 15.2
Release:	15.2
Codename:	n/a
sauer@orthos:~> snapper --version
snapper 0.8.9
flags btrfs,lvm,no-ext4,xattrs,rollback,btrfs-quota,no-selinux
sauer@orthos:~> awk '$1=="overlay"' /etc/fstab | wc -c
4088
sauer@orthos:~> awk '$1=="overlay"' /etc/fstab
overlay           /etc                    overlay  defaults,upperdir=/sysroot/var/lib/overlay/196/etc,lowerdir=/sysroot/var/lib/overlay/183/etc:/sysroot/var/lib/overlay/170/etc:/sysroot/var/lib/overlay/169/etc:/sysroot/var/lib/overlay/168/etc:/sysroot/var/lib/overlay/167/etc:/sysroot/var/lib/overlay/165/etc:/sysroot/var/lib/overlay/164/etc:/sysroot/var/lib/overlay/163/etc:/sysroot/var/lib/overlay/162/etc:/sysroot/var/lib/overlay/161/etc:/sysroot/var/lib/overlay/160/etc:/sysroot/var/lib/overlay/159/etc:/sysroot/var/lib/overlay/158/etc:/sysroot/var/lib/overlay/157/etc:/sysroot/var/lib/overlay/156/etc:/sysroot/var/lib/overlay/155/etc:/sysroot/var/lib/overlay/154/etc:/sysroot/var/lib/overlay/153/etc:/sysroot/var/lib/overlay/152/etc:/sysroot/var/lib/overlay/151/etc:/sysroot/var/lib/overlay/150/etc:/sysroot/var/lib/overlay/149/etc:/sysroot/var/lib/overlay/148/etc:/sysroot/var/lib/overlay/147/etc:/sysroot/var/lib/overlay/146/etc:/sysroot/var/lib/overlay/145/etc:/sysroot/var/lib/overlay/144/etc:/sysroot/var/lib/overlay/143/etc:/sysroot/var/lib/overlay/142/etc:/sysroot/var/lib/overlay/141/etc:/sysroot/var/lib/overlay/140/etc:/sysroot/var/lib/overlay/139/etc:/sysroot/var/lib/overlay/138/etc:/sysroot/var/lib/overlay/137/etc:/sysroot/var/lib/overlay/136/etc:/sysroot/var/lib/overlay/135/etc:/sysroot/var/lib/overlay/134/etc:/sysroot/var/lib/overlay/133/etc:/sysroot/var/lib/overlay/132/etc:/sysroot/var/lib/overlay/131/etc:/sysroot/var/lib/overlay/130/etc:/sysroot/var/lib/overlay/129/etc:/sysroot/var/lib/overlay/128/etc:/sysroot/var/lib/overlay/127/etc:/sysroot/var/lib/overlay/126/etc:/sysroot/var/lib/overlay/125/etc:/sysroot/var/lib/overlay/124/etc:/sysroot/var/lib/overlay/123/etc:/sysroot/var/lib/overlay/122/etc:/sysroot/var/lib/overlay/121/etc:/sysroot/var/lib/overlay/120/etc:/sysroot/var/lib/overlay/119/etc:/sysroot/var/lib/overlay/118/etc:/sysroot/var/lib/overlay/117/etc:/sysroot/var/lib/overlay/116/etc:/sysroot/var/lib/overlay/115/etc:/sysroot/var/lib/overlay/114/etc:/sysroot/var/lib/overlay/113/etc:/sysroot/var/lib/overlay/112/etc:/sysroot/var/lib/overlay/111/etc:/sysroot/var/lib/overlay/110/etc:/sysroot/var/lib/overlay/109/etc:/sysroot/var/lib/overlay/108/etc:/sysroot/var/lib/overlay/107/etc:/sysroot/var/lib/overlay/106/etc:/sysroot/var/lib/overlay/105/etc:/sysroot/var/lib/overlay/104/etc:/sysroot/var/lib/overlay/103/etc:/sysroot/var/lib/overlay/102/etc:/sysroot/var/lib/overlay/101/etc:/sysroot/var/lib/overlay/100/etc:/sysroot/var/lib/overlay/99/etc:/sysroot/var/lib/overlay/98/etc:/sysroot/var/lib/overlay/97/etc:/sysroot/var/lib/overlay/96/etc:/sysroot/var/lib/overlay/95/etc:/sysroot/var/lib/overlay/94/etc:/sysroot/var/lib/overlay/93/etc:/sysroot/var/lib/overlay/92/etc:/sysroot/var/lib/overlay/91/etc:/sysroot/var/lib/overlay/90/etc:/sysroot/var/lib/overlay/89/etc:/sysroot/var/lib/overlay/88/etc:/sysroot/var/lib/overlay/87/etc:/sysroot/var/lib/overlay/86/etc:/sysroot/var/lib/overlay/85/etc:/sysroot/var/lib/overlay/84/etc:/sysroot/var/lib/overlay/83/etc:/sysroot/var/lib/overlay/82/etc:/sysroot/var/lib/overlay/81/etc:/sysroot/var/lib/overlay/80/etc:/sysroot/var/lib/overlay/79/etc:/sysroot/var/lib/overlay/78/etc:/sysroot/var/lib/overlay/77/etc:/sysroot/var/lib/overlay/76/etc:/sysroot/var/lib/overlay/75/etc:/sysroot/var/lib/overlay/74/etc:/sysroot/var/lib/overlay/73/etc:/sysroot/var/lib/overlay/72/etc:/sysroot/var/lib/overlay/71/etc:/sysroot/var/lib/overlay/70/etc:/sysroot/var/lib/overlay/69/etc:/sysroot/var/lib/overlay/68/etc:/sysroot/var/lib/overlay/67/etc:/sysroot/var/lib/overlay/66/etc:/sysroot/var/lib/overlay/65/etc:/sysroot/var/lib/overlay/64/etc:/sysroot/var/lib/overlay/63/etc:/sysroot/var/lib/overlay/52/etc:/sysroot/var/lib/overlay/51/etc:/sysroot/var/lib/overlay/50/etc:/sysroot/var/lib/overlay/49/etc:/sysroot/var/lib/overlay/48/etc:/sysroot/var/lib/overlay/47/etc:/sysroot/etc,workdir=/sysroot/var/lib/overlay/work-etc,x-systemd.requires-mounts-for=/var,x-systemd.requires-mounts-for=/var/lib/overlay,x-systemd.requires-mounts-for=/sysroot/var,x-systemd.requires-mounts-for=/sysroot/var/lib/overlay,x-initrd.mount  0  0
sauer@orthos:~> sudo snapper list
   # | Type   | Pre # | Date                            | User | Used Space | Cleanup | Description             | Userdata     
-----+--------+-------+---------------------------------+------+------------+---------+-------------------------+--------------
  0  | single |       |                                 | root |            |         | current                 |              
 47  | single |       | Thu 11 Jun 2020 12:38:16 AM CDT | root |  71.88 MiB | number  | Snapshot Update of #46  | important=yes
 48  | single |       | Fri 12 Jun 2020 01:52:53 AM CDT | root |  19.04 MiB | number  | Snapshot Update of #47  | important=yes
 49  | single |       | Sat 13 Jun 2020 01:45:37 AM CDT | root |   1.32 MiB | number  | Snapshot Update of #48  | important=yes
 50  | single |       | Sun 14 Jun 2020 01:45:19 AM CDT | root |  29.41 MiB | number  | Snapshot Update of #49  | important=yes
 51  | single |       | Mon 06 Jul 2020 12:37:15 AM CDT | root | 248.23 MiB | number  | Snapshot Update of #50  | important=yes
172  | single |       | Tue 23 Feb 2021 11:15:03 AM CST | root | 527.94 MiB | number  | rollback backup of #171 | important=yes
195  | single |       | Thu 11 Mar 2021 12:42:39 PM CST | root |  77.04 MiB | number  | writable copy of #183   |              
196* | single |       | Thu 11 Mar 2021 10:26:23 PM CST | root |   8.26 MiB |         | Snapshot Update of #195 |              
199  | single |       | Fri 26 Mar 2021 08:32:44 PM CDT | root |  79.48 MiB | number  | Snapshot Update of #196 |              
200  | single |       | Sat 27 Mar 2021 01:40:10 AM CDT | root | 756.93 MiB |         | Snapshot Update of #196 |              
```

**Comment by thkukuk** [comment]
Sounds like transactional-server system role. That's only Tech-Preview, you should upgrade to Leap 15.3 to get all the changes and fixes to transactional-update (at least Leap 15.3 should have them).

**Comment by dannysauer** [comment]
So, any upgrade adds a new fstab overlay entry, which renders the system unbootable. :D I guess I can roll back a step and then upgrade, but I was hoping to clean this "150 overlays for 10 snapshots" mess up before upgrading. :)

**Comment by laenion** [comment]
The commits you are looking for is 80ce1c275d26df49b285d52fb6d6bd0073d4b8c3 (3.x series, C++) / f28df8af4a6a9df295aea75c7f0f4eb492adfe70 (2.x series, Bash), available since version 2.25 :-)

Both the old and the new overlay behavior are described in the transactional-update guide:
* Old behavior: https://github.com/openSUSE/transactional-update/blob/v2.23/doc/transactional-update.xml#L437
* Current hehavior: https://kubic.opensuse.org/documentation/transactional-update-guide/tu-setup.html#tu-setup-etc

The old behavior in a nutshell: All overlays until the one of the _oldest still available snapshot_ snapshots are preserved, because you _could_ still boot into snapshot 47 and change something there. That behavior was changed with the above commits, only changes to the previously booted snapshot will be visible in the current snapshot.

Now the really big question is: Are you keeping those old snapshots intentionally?

If so, you could indeed flatten the overlay directories of the non-existing snapshots manually by recursively copying the contents from the lowest to the highest snapshot into a new directory and use that one instead (i.e. copy the contents of all the listed overlay directories in `/etc/fstab` between snapshot number `51` and `172` into `/var/lib/overlay/51/etc` and delete them from the fstab entry).

**Comment by dannysauer** [comment]
Not intentionally keeping the intermediate ones, but the rationale for them existing makes sense. Flattening by incremental copying sounds easier than the overlay mount process I was considering. I'd knock out a script, but since this issue seems to be exclusive to old versions it'd probably not be real helpful to anyone else.

Thanks!

**Comment by laenion** [comment]
You can add the script to this ticket if you write it anyway - one can never know who is still using older versions :-)

Closing this ticket for now.
