### ISSUE TITLE
transactional-update reboot fallback systemd causing forced reboots without conf

### ISSUE THREAD

**Issue by Xathros1** [openSUSE/transactional-update#95]
I'd suggest to change this fallback default from systemd (systemctl reboot) to none. 
This also would make it possible to deactivate any automatic reboots entirely without changing config. (REBOOT_METHOD) by just deactivating rebootmgr.service.

"reboot
Trigger a reboot after updating the system.

Several different reboot methods are supported, configurable via the REBOOT_METHOD configuration option in [transactional-update.conf(5)](https://manpages.opensuse.org/Tumbleweed/transactional-update/transactional-update.conf.5.en.html). By default [rebootmgrd(8)](https://manpages.opensuse.org/Tumbleweed/rebootmgr/rebootmgrd.8.en.html) will be used to reboot the system according to the configured policies if the service is running, otherwise systemctl reboot will be called."
https://manpages.opensuse.org/Tumbleweed/transactional-update/transactional-update.8.en.html

**Comment by thkukuk** [comment]
That would break the reboot option completely.

If you don't want to reboot, don't specify the reboot argument. Quite simple.
And yes, even systemd service files are configureable for exactly this reason.
And yes, if you don't like the default, configuration files are exactly for this case.

**Comment by Xathros1** [comment]
Why would it break reboot option completly? It checks reboomgr, if it isn't available it would do no automatic reboot.

**Comment by Xathros1** [comment]
> Why would it break reboot option completly? It checks rebootmgr, if it isn't available it would do no automatic reboot.

**Comment by Xathros1** [comment]
> If you don't want to reboot, don't specify the reboot argument.

If you don't set the reboot argument, then it will use AUTO, which will force reboot at system update via systemd

**Comment by laenion** [comment]
The question is: Instead of disabling `rebootmgr.server`, wouldn't it be easier to call `systemctl edit transactional-update.service` and change the `ExecStart` line to not include the `reboot` option?

**Comment by thkukuk** [comment]
> > If you don't want to reboot, don't specify the reboot argument.
> 
> If you don't set the reboot argument, then it will use AUTO, which will force reboot at system update via systemd

Please test that before you write such a nonsense.
transactional-update only triggers a reboot, if you specify the "reboot" argument, else it will not reboot.
If you specify the "reboot" option, transactional-update has a list of possibilities, which can be used to trigger a reboot. Which one is used depends on your configuration.
If this configuration is "auto", it tries first rebootmgrd, and if that is not running, it uses systemd.

**Comment by Xathros1** [comment]
> Please test that before you write such a nonsense. transactional-update only triggers a reboot, if you specify the "reboot" argument, else it will not reboot.

I'm no programmer and I have nothing to do with your development, however the fact still remains that it's using reboot per default? So, that's the cause. finally.

**Comment by thkukuk** [comment]
> The question is: Instead of disabling `rebootmgr.service`, wouldn't it be easier to call `systemctl edit transactional-update.service` and change the `ExecStart` line to not include the `reboot` option?

The disabling of `rebootmgr.service` in the MicroOS Desktop Portal is plain wrong. No idea who wrote that, but he did clearly never read the transactional-update manual page.

And yes, changing the `ExecStart` line to not include the `reboot` option is the correct way, if you want to keep the reboot option for a manual call working.

But much simpler would be to to disable the transactional-update.timer, since this doesn't make any sense  if you don't reboot.

**Comment by laenion** [comment]
> But much simpler would be to to disable the transactional-update.timer, since this doesn't make any sense if you don't reboot.

Indeed, that would be the simplest option.

**Comment by Xathros1** [comment]
It does make sense in the way that you'd want to have automatic updates without forced reboots? 
I've tried the command line? Idk what you're suggesting here, but I wouldn't want this default changed if it force a reboot on me while I was working, without knowing that it would happen. (no major thing but still)

**Comment by Xathros1** [comment]
> > But much simpler would be to to disable the transactional-update.timer, since this doesn't make any sense if you don't reboot.
> 
> Indeed, that would be the simplest option.

without that notifications won't work however?

**Comment by laenion** [comment]
Won't notifications need `notify` as the reboot method anyway?

**Comment by Xathros1** [comment]
> Won't notifications need `notify` as the reboot method anyway?

Yes, they need notify as far as I'm aware. But would that trigger without reboot specified? I haven't tried that out

About the stuff with rebootmgr, Idk who initially wrote that. I've already changed some stuff today, but it seems I'd rather cut that stuff out completly then.

**Comment by Xathros1** [comment]
btw could I just change transactional-update.service and change the ExecStart line to not include the reboot and add notify? Instead of adding a conf to /etc/? Would that be reset with updates?

**Comment by Xathros1** [comment]
> btw could I just change transactional-update.service and change the ExecStart line to not include the reboot and add notify?
It just creates an error. :(

> changing the `ExecStart` line to not include the `reboot` option is the correct way, if you want to keep the reboot option for a manual call working.

Thanks that answered my initial suggestion, as it won't trigger reboot without conf. 

An easier way to switch to notification, would be helpful. I'd personally like to just stick to changing the transactional-update.service without needing to touch any conf file, but whatever.

**Comment by laenion** [comment]
Both systemd and transactional-update support config drop-ins, so you will only declare the **differences** to the original config file in _/etc_. That way you just explicitly declare where you don't want to follow the default settings, but all other configuration changes (e.g. on security updates) will still be taken from the default configuration (i.e. the file from the package).

Let's take the file _/usr/lib/systemd/system/transactional-update.service_ as an example. If you call `systemctl edit transactional-update.service` and add
```
[Service]
ExecStart=/usr/sbin/transactional-update cleanup ${UPDATE_METHOD}
```
to it, a file called _/etc/systemd/system/transactional-update.service.d/override.conf_ will be created containing only those two lines; for all the other settings the system configuration file is used.
Something very similar is done when you enable or disable a service by the way: This will create or delete the symlink _/etc/systemd/system/multi-user.target.wants/rebootmgr.service_ in your case, i.e. only the admin specific part is stored in _/etc_.

In _/etc/transactional-update.conf_ you should also only add the lines you really want to change, everything else will be taken from the default configuration.


I didn't follow development of the notifier recently, but I think we can work out something that doesn't require manual intervention. I'm just too busy currently to push this forward myself.

**Comment by Xathros1** [comment]
@laenion thanks for your input. I didn't know of any best practices, so this was very helpful.
I've had the time and changed the wiki/portal/whatever accordingly. I hope it's now a bit more helpful for Newcomers.
